### ISSUE TITLE
Window Controls on multiple-windows selection screen are not Numix

### ISSUE THREAD

**Issue by SimpleAnecdote** [numixproject/numix-gtk-theme#140]
Hello! First time posting an issue for this project so please excuse any newbish mistakes.

So the issue is: on multiple-windows-of-the-same-program selection screen, there are window controls (close, minimise, maximise) for the selection screen which are Ubuntu's default theme and not Numix.

OS: Ubuntu 14.04 64bit (with Unity)

Here's a screenshot (look at top left):
![numix-circle - 2014 05 27 - chrome 35 and copy tray icons](https://cloud.githubusercontent.com/assets/1707719/3088211/b4c311f0-e56a-11e3-938e-7b0564e02608.png)

Theme is fantastic by the way!

**Comment by satya164** [comment]
@me4oslav can you look into the issue?

**Comment by mzur** [comment]
Should be fixed by 526089eb4c21c533b0529c623d377154666987ea (not yet released, though). @SimpleAnecdote can you confirm this?

**Comment by SimpleAnecdote** [comment]
@mzur - has this been released? I'm still experiencing the same behaviour.

**Comment by mzur** [comment]
@SimpleAnecdote It has been released in [v2.3](https://github.com/shimmerproject/Numix/releases/tag/v2.3).
