### ISSUE TITLE
GTK 3.14 support

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#155]
Earlier, I updated the GTK3 toolkit to GTK 3.14, which is came out earlier with GNOME 3.14. Right now the theme is now messed up with glitches—such as the toolbars are in a bad shape with hover elements and popover text are not visible over light-themed GTK3 apps:

![screenshot](https://cloud.githubusercontent.com/assets/6704448/4400331/375f98ea-447f-11e4-9b93-0c34880a7e34.png)

Messed up toolbars:

![screenshot](https://cloud.githubusercontent.com/assets/6704448/4400385/f36eb8fe-447f-11e4-9f13-c8f885fb6f1c.png)

Checkboxes and radio buttons are likely unthemed, and almost gone, too:

![screenshot-1](https://cloud.githubusercontent.com/assets/6704448/4400370/c9fb796c-447f-11e4-8500-2ab2200a07f2.png)

Desktop environment used is MATE under Antergos/Arch.

**Comment by toupeira** [comment]
Similar issues on Gnome 3 and Xfce, both running Debian sid and Numix 2.3+310~201408042031~ubuntu14.10.1 from the PPA.

**Comment by Realex-fire** [comment]
same problem, gtk3.14 not supported.

**Comment by toupeira** [comment]
Also confirmed in the latest update 2.3+312~201409292317~ubuntu14.10.1, it didn't seem to improve anything.

**Comment by progandy** [comment]
Radio, checkbox, expander, spinner now use -gtk-icon-source instead of background-image to set the necessary icons. I copied those sections from Adwaita and can confirm it works in principle, even if a bit ugly. My steps:
Remove the block for _@keyframes spinner_ from Numix
Add the blocks for _GtkExpander, @keyframes spin, .cursor-handle, .check, and .radio_ from Adwaita to Numix

**Comment by spacepluk** [comment]
I'm also having some problems with checkboxes on 3.14

![screenshot from 2014-10-11 10 33 16](https://cloud.githubusercontent.com/assets/824762/4601838/4ea558f4-5119-11e4-9eb0-99f601cf6621.png)

**Comment by ghost** [comment]
Not only that, the theme was no square boundaries within some groupboxes (as mentioned above as I seen, bolded text only) and status bars. But now it is a mere glitch as well.

Here's the status bar looked like right now, it looks thicker than ever:

![screenshot-character map](https://cloud.githubusercontent.com/assets/6704448/4607223/b5b9d420-5245-11e4-83d3-2ca2d72a9fde.png)

**Comment by ghost** [comment]
GTK 3.14 is now at the stable repos in Arch Linux. This theme should be fixed soon.

**Comment by achadwick** [comment]
Confirmed on Debian testing/unstable (Jessie/Sid) with libgtk-3-0 3.14.1-1, and Numix 31c7d6ec0dc4fb09e760f5d7c5ee757b6e431e1a.

The contents of a `GtkPopover` can't be seen unless the mouse pointer rolls over them:

![gedit popover rendering bug in numix](https://cloud.githubusercontent.com/assets/61299/4684215/4257192e-562e-11e4-92fd-3292a9ce259c.png)

It looks as though the background should be the dark colour, not light.

Checkbox icons are not shown. Radio buttons too, probably. This is fairly serious: it renders any GTK3 preferences dialog with checkboxes unusable:

![gedit preferences checkbox rendering bug in numix](https://cloud.githubusercontent.com/assets/61299/4684219/4c2b0c58-562e-11e4-9deb-c270551ca61e.png)

The top seven options are turned on, though you'd be forgiven for not knowing their state.

Gtk 3.14 or beyond will be part of the next stable Debian release. I hope this bug will be fixed soon.

**Comment by abihf** [comment]
to fix the popover problem, i added this style to ~/.config/gtk-3.0/gtk.css

``` css
.popover GtkLabel, .popover GtkImage {
    color: @theme_fg_color;
}
```

**Comment by Mechazawa** [comment]
Is there a fix for the checkboxes not working yet?

**Comment by abihf** [comment]
[this theme](https://github.com/horst3180/Vertex-theme) works. and i have no idea. may be because it has [assets.txt](https://github.com/horst3180/Vertex-theme/blob/master/Vertex-gtk/gtk-3.0/assets.txt) or [assets.svg](https://github.com/horst3180/Vertex-theme/blob/master/Vertex-gtk/gtk-3.0/assets.svg)

i use arch linux, and gtk 3.14 is now in stable repo. so i switch to another theme

**Comment by satya164** [comment]
Work is going on for 3.14 in this branch https://github.com/shimmerproject/Numix/tree/sass

Anyone is welcome to help.

**Comment by spacepluk** [comment]
Hey satya, do I need to do anything special to test the SASS version?  I don't see any compilation scripts and I if check out that branch it looks like this:

![wolu39x](https://cloud.githubusercontent.com/assets/824762/4693370/63293b0e-5797-11e4-8856-eef839a5225a.jpg)

So I assume I'm doing something wrong.

**Comment by satya164** [comment]
You need to install SASS, then inside the gtk-3.0 folder, you need to run
"sass --watch src:gen". I'll write a script some day.

Note that the port is in a very very early stage.

**Comment by spacepluk** [comment]
Thanks, I just tried with the SASS version but for some reason the dark theme doesn't work and I still get the same thing with the checkboxes. The code looks good though :)

If you find out what happens with the checkboxes it might be a good idea to backport the fix to the css version so we can keep using the theme while you rework the code.

**Comment by emariz** [comment]
I am also experiencing this problem in Debian Testing, using the latest Numix theme from GitHub.
There seems to be an inversion of the menus colour references, which makes impossible to read them.

![gedit](https://cloud.githubusercontent.com/assets/9307858/4694082/3b4150f8-57bb-11e4-9dba-29134fe1788f.png)

![calculator](https://cloud.githubusercontent.com/assets/9307858/4694081/3b3c2da8-57bb-11e4-9101-b4d9204c41bf.png)

.
.
This also affects in-window application menus, which is a must for users who use focus-follows-mouse and thus disable panel bar menus.

![menu_nautilus](https://cloud.githubusercontent.com/assets/9307858/4694098/b15b0f22-57bb-11e4-844c-10caa26901c8.png)

![menu_calculator](https://cloud.githubusercontent.com/assets/9307858/4694097/b1583a72-57bb-11e4-80b6-471189498f0b.png)

.
.
One can read the menus by inverting the colour references, but it also affects the title bars.

![colour_references](https://cloud.githubusercontent.com/assets/9307858/4694086/509238a0-57bb-11e4-9bd1-a2c927eeae50.png)

.
.
As other users have stated, bullets and check boxes are also unavailable, making it impossible to set a preference.

![check_screenshot](https://cloud.githubusercontent.com/assets/9307858/4694109/5eb5edd6-57bc-11e4-8cd5-7a9095215301.png)

.
.
Hope to have a fix to these problems soon.
Let me know if you need more information.

**Comment by satya164** [comment]
@spacepluk As I said, it's in very very early stage. Lots of styles aren't there yet.

**Comment by seankhl** [comment]
@satya164 Do you have any idea when the theme will be ready? I love your theme and want to continue using it ASAP.

**Comment by satya164** [comment]
@seanlaguna It's very lengthy process. I cannot give an exact timeline.

**Comment by ryanvade** [comment]
I have noticed that when using Numix themes on Unity for Arch (gtk 3.14) the incicators are put in scrolling mode for no reason . 

![menu_015](https://cloud.githubusercontent.com/assets/1910293/4708682/86250d6a-5899-11e4-9234-435b07863a54.png)

**Comment by seankhl** [comment]
@satya164 Thanks for the merge/commit earlier today. I can verify that checkboxes are now visible and a few other small things seem to have been fixed (I hadn't updated in a while). But, some things are still broken of course, primarily the spacings on some outlines and boxes. When your 3.14 build comes out and if it works smoothly when I test it, I will purchase Numix.

**Comment by spacepluk** [comment]
Thanks for merging the workaround, the colors are a bit off but now we can see what we are doing with the checkboxes :)

![fwskxmh](https://cloud.githubusercontent.com/assets/824762/4714009/2d8f14e6-58eb-11e4-9e45-b00b662105e5.png)

**Comment by progandy** [comment]
For your new sass port I'd suggest you look at the definitions which are being written for the official HighContrast theme.
[GNOME hc-sass](https://github.com/GNOME/gnome-themes-standard/blob/wip/hc-sass/themes/HighContrast/gtk-3.0/_common.scss)

**Comment by pocketpc** [comment]
Is there someplace to discuss the current progress on sass? It doesn't look like anyone's touched it for a while, and I'd like to help. However, I have no idea what's been done and what needs to be done.

**Comment by satya164** [comment]
If you like to help, you can reach me on hangouts :)

Thanks :D

**Comment by khurshid-alam** [comment]
I hope, while it is porting to saas, it will keep support for other desktop-shell as well (like Unity, Mate, Flashback. Cinnamon..etc)

**Comment by ebkalderon** [comment]
Just curious, any progress on this?

**Comment by satya164** [comment]
Yeah, right now I've managed to make nautilus and Tweak tool look decent.

On 18 November 2014 11:11, Eyal Kalderon notifications@github.com wrote:

> Just curious, any progress on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shimmerproject/Numix/issues/155#issuecomment-63425363
> .

## 

Satyajit Sahoo
Digital artist
DeviantArt Profile http://satya164.deviantart.com

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by skmexyz** [comment]
Any idea how to remove the lines around these? (they seriously look ugly) 
Ubuntu 14.10 Gnome 3.14
![screenshot from 2014-11-19 11 10 05](https://cloud.githubusercontent.com/assets/2701579/5109066/b7e12f64-6fdc-11e4-86e6-fb881536c711.png)

**Comment by aphirst** [comment]
It's incredibly frustrating that almost every new version of GTK3 breaks support with themes. My previously favourite themes, Zukitwo-colors, were (to the best of my knowledge) discontinued for this reason. I sincerely hope that the Numix project continues to go strong, as otherwise there are _no_ themes which work for both GTK2 and GTK3 which look anywhere near as good as it does, or as Zukitwo-colors did.

**Comment by satya164** [comment]
Latest commits address some of the issues. Please test and let me know of other bugs.

**Comment by Vladimir-csp** [comment]
There is also a problem with buttons. There is no distinction between pressed and released buttons.
Here is an example from remmina toolbar:
![buttons](https://cloud.githubusercontent.com/assets/4061903/5158196/9f31c458-7345-11e4-99ab-0e4682643204.png)
Two greyed out buttons you see are just inactive, but some of other buttons on the right are really pressed down. No way to tell if keyboard grab is enabled or disabled here. And overall visual clutter present.
Here is a screenshot with older GTK:
![oldbuttons](https://cloud.githubusercontent.com/assets/4061903/5158255/6aa9e92a-7347-11e4-8aa0-932500b29680.png)
Unpressed buttons have no decoration, pressed are clearly marked.

**Comment by satya164** [comment]
@Vladimir-csp Pressed buttons should work with latest master.

**Comment by Vladimir-csp** [comment]
It seems, I failed to kill remmina properly before testing.

**Comment by Vladimir-csp** [comment]
Pressed buttons now look very similar to inactive buttons, except the icon is not greyed out. With monochrome icon themes it would be hard to distinguish.
![newbuttons](https://cloud.githubusercontent.com/assets/4061903/5158305/9c83900c-7349-11e4-8d12-b47d56ccc22f.png)
Is showing toolbar button decoration now mandatory in GTK?

**Comment by satya164** [comment]
They looked that way previously. The issue is with the borders. I'll try to investigate why they are there.

**Comment by satya164** [comment]
@Vladimir-csp this issue should be fixed with the latest commits.

**Comment by satya164** [comment]
Most of the issues in GTK3.14 have been taken care of. If there are any more issues, feel free to reopen the issue.

**Comment by Tasqa** [comment]
I'm still having issues with checkboxes. The checkmark does not show when you "checked" a item in a list when it is also selected in the list. 

Unselected:
![screenshot from 2014-12-22 11 55 22](https://cloud.githubusercontent.com/assets/2271762/5524147/bd9e67a0-89d1-11e4-9067-13672d81d7a9.png)

Selected:
![screenshot from 2014-12-22 11 55 24](https://cloud.githubusercontent.com/assets/2271762/5524151/cbd14a54-89d1-11e4-941b-15c41712cc85.png)

**Comment by satya164** [comment]
What is the name of the app?

**Comment by Tasqa** [comment]
its the gui of firewalld

**Comment by satya164** [comment]
@Tasqa the issue should be fixed now.

**Comment by Tasqa** [comment]
It seems to work properly again. Thank you!

**Comment by lorienhu** [comment]
I realize this is not the right repo for this, but I wasn't sure where else to comment since I couldn't find an issue tracker for Numix Light. I just got Numix Light today and it seems that a lot of the issues in here have not been fixed for that theme. I have the same issues as the images posted here: the bars across Gnome Tweak tool, and the invisible boxes, specifically.

**Comment by kr428** [comment]
Same as @lorienhu, regular Numix on GTK 3.14 / GNOME-Ubuntu 14.04. :|

**Comment by satya164** [comment]
Shoot us an email at team @numixproject.org to get the latest version

**Comment by nico-dela** [comment]
Hey! I'm using Elementary OS 0.3 Freya (64 bit) (Built on Ubuntu 14.04) 

Any idea how to remove the lines around Applications menu? (they seriously look ugly...)

![screenshot from 2015-05-28 00 54 28](https://cloud.githubusercontent.com/assets/3194614/7852691/2e5eb2b6-04d8-11e5-8f6b-9403a521c920.png)

**Comment by nico-dela** [comment]
Hey. it's me again.... Do you have any clue for solve this glitch at time & date?
![screenshot from 2015-05-28 00 56 26](https://cloud.githubusercontent.com/assets/3194614/7852712/8aecf22c-04d8-11e5-8425-d960de454553.png)

I don't know which version of GTK i'm using, I tried this command:

dpkg -l libgtk2.0-0 libgtk-3-0

And get next result: 

||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libgtk-3-0:amd 3.14.13-0ubu amd64        GTK+ graphical user interface lib
ii  libgtk2.0-0:am 2.24.23-0ubu amd64        GTK+ graphical user interface lib
ii  libgtk2.0-0:i3 2.24.23-0ubu i386         GTK+ graphical user interface lib

Please, I need your help!, it also repeats on Sound, Networking, Alerts and Power Buttons that are at top right of the desktop

Sorry my english is so poor... haha

**Comment by satya164** [comment]
@delacruzbordajn ElementaryOS uses custom widgets called granite. We don't support granite right now, but we'll soon.

**Comment by nico-dela** [comment]
Have some notice?

**Comment by ghost** [comment]
I have the same issue with check boxes.
This is a really good example
`zenity --list --checklist --column=A --column=B C C D D E E F F`
![nochex](https://cloud.githubusercontent.com/assets/4912582/12858007/03e212dc-cc13-11e5-99a3-3faa032d0a13.png)
There are no boxes for the checkbox.
Is there a workaround for this issue until it is fixed??
I have tested this on Debian Jessie 8 and Ubuntu 16.04
Both with up to date Numix (from the PPA)

**Comment by khurshid-alam** [comment]
On Ubuntu 16.04, remove ppa and just type `sudo apt-get install numix-gtk-theme` This will fix the iisue.

![image1](http://i.imgur.com/lt6Yn0q.png)

**Comment by ghost** [comment]
@khurshid-alam
Thanks very much!!!
What can be done for Debian, though?  Is there a specific version that is working in the PPA?
I am part of the ToriOS dev team, and we use Numix as the default theme and Numix-Circle as the default icon theme.  We have had the PPA and it was working fine for quite some time.
ToriOS is now based on Debian, so that is my main concern in my question.

**Comment by khurshid-alam** [comment]
@Israel- PPA will be fixed soon.

**Comment by ghost** [comment]
@khurshid-alam You guys are amazing!  Thank you SO MUCH!!!!!!!!!!!

**Comment by ghost** [comment]
@khurshid-alam The PPA still has this issue with check boxes, at least for the trusty PPA.
Should I use the Xenial PPA instead?
It works in Ubuntu Xenial.
However using the trusty PPA in Debian Jessie I still have this issue

**Comment by khurshid-alam** [comment]
@Israel- Trusty has Gtk-3.10. And we dropped support for anything below 3.16.
