### ISSUE TITLE
Invalid desktop background with Nautilus (version of the theme: 3.0)

### ISSUE THREAD

**Issue by ItachiSan** [numixproject/numix-gtk-theme#272]
Hey,
I just installed the new version (**3.0**) of the theme on my **ArchLinux** (**_Antergos**_) and I have a weird white background on _Nautilus_.
![schermata da 2015-12-01 11-02-46](https://cloud.githubusercontent.com/assets/1223421/11497727/35fe575c-981b-11e5-8560-7916a8168ffb.png)
Killing Nautilus (with `nautilus -q`) fixes it:
![schermata da 2015-12-01 11-03-10](https://cloud.githubusercontent.com/assets/1223421/11497736/4c5a3bba-981b-11e5-9a46-595fc085070a.png)
Also, switching the _GTK_ option in the **Tweak Tool** fixes it.

**Comment by ankitstarski** [comment]
I have the same problem, when you turn on desktop icons from `gnome-tweak-tool` and apply Numix theme, the Desktop background is overlayed by a whitish opaque background.

I'm using Fedora 23 running GNOME 3.18.1

I think the title of this issue could be better. :)

**Comment by ItachiSan** [comment]
@ankitstarski Suggestions for the title?

**Comment by ankitstarski** [comment]
Invalid desktop background?

**Comment by k01uch** [comment]
Fedora 23, add in theme folder (eg. /usr/share/themes/Numix/gtk-3.0/dist/gtk.css (& gtk-dark.css)) in Nautilus section:
**NautilusDesktopWindow GtkWidget { background-color: transparent; }**

and run:
**glib-compile-resources gtk.gresource.xml**
in /usr/share/themes/Numix/gtk-3.0

Hope it helps.

**Comment by axfelix** [comment]
Glad I found this issue, but it's starting to crop up elsewhere so it should hopefully be fixed upstream:

https://forum.antergos.com/topic/3294/desktop-wallpaper-goes-gray-but-it-configured-for-an-image
https://github.com/numixproject/numix-icon-theme/issues/991#issuecomment-171768436

**Comment by axfelix** [comment]
The suggested change to gtk.css and gtk-dark.css Unfortunately doesn't seem to be working.

**Comment by axfelix** [comment]
Also tried stealing this from the Arc theme and it isn't working either:

NautilusWindow NautilusWindowSlot {
  background-color: #ffffff; }

NautilusDesktopWindow NautilusWindowSlot {
  background-color: transparent; }

**Comment by axfelix** [comment]
Manage to fix it by removing

background-color: #f0f0f0;

from NautilusWindow GtkPaned, NautilusWindow GtkPaned:hover {

in gtk.css, and recompiling the theme as described above.

I'm assuming that background colour should be defined elsewhere in Gtk 3.18+ ? No idea where though, I'm just hacking as I go.

**Comment by k01uch** [comment]
Strange, my fix works on two different machines with Fedora 23 Server and Workstation edition. I'll try your fix.

**Comment by axfelix** [comment]
My posted "fix" is in combination with the stuff I stole from Arc in the above comment, btw. I'm not an Antergos maintainer (and technically I've removed some Nautilus background colours from non-desktop windows, I think, which is a regression) so I'm not going to try isolating it for now...

I'm on Antergos so there's a slim chance that I have a newer Gtk than you and thus a more complicated workaround is required, though I'd be surprised if you still had an apparently smaller breakage (occam's razor).

**Comment by acutbal** [comment]
Hi,

I've noticed that the background of Nautilus becomes grey only if you select icon list view and the zoom level at 100%. If you change one of this settings (list view or another % of zoom) then there is no problem.

Hope this helps, best regards!! :smile:

**Comment by khurshid-alam** [comment]
Related bug https://bugzilla.gnome.org/show_bug.cgi?id=761965

commit-> https://github.com/GNOME/nautilus/commit/b71b236b9ef6fb7793658ce0e669b2631efcca17

Which tries to fix the issue

**Comment by GabVenturato** [comment]
Hi, I have the same problem in fedora 22 after last Numix theme update. More precisely after the last dnf update made yesterday, after reboot appeared the problem.
(I have GNOME Shell 3.16.4)

I've solved with the k01uch fix. I don't understand if it is a Numix bug or a Nautilus bug..? 
Thanks.

**Comment by khurshid-alam** [comment]
Yes, any update will overwrite any local fixes...which you need to re-apply. And its a bug in nautilus. It doesn't happen under Ubuntu because of patches, but it is already fixed in nautilus 3.20. We need to wait and see.

**Comment by geckolinux** [comment]
@khurshid-alam  Hmm, in Nautilus 3.20.1 on openSUSE Tumbleweed this is still an issue.

**Comment by axfelix** [comment]
Yeah, not fixed on Arch on 3.20 either

**Comment by geckolinux** [comment]
Is there a relevant Nautilus bug report for this?

**Comment by caribpa** [comment]
The workaround I've found for **3.20** using Numix-Frost-Light theme is:
In **_/usr/share/themes/Numix-Frost-Light/gtk-3.20/dist/gtk.css_** find .**nautilus-window paned, .nautilus-window paned:hover** {...} and replace the _background-color_ value with _transparent_.
It will also works with gtk-dark.css (the global dark theme) as long as you follow the same steps for changing the background value.

Then you compile the changes as described in other comments:
**glib-compile-resources gtk.gresource.xml**

Be sure you are in the _/usr/share/themes/Numix-Frost-Light/gtk-3.20_ folder before running the command.

Then **refresh the theme** by changing to any other in tweak tool and getting back to Numix-Frost-Light, you will see the changes after that.

It also works with Numix-Frost though you have to redo the steps using the Numix-Frost folder instead of Numix-Frost-Light.

Note that I'm not sure if this workaround will also change the background of any other Nautilus window but so far I did not notice anything.

**Comment by k01uch** [comment]
I wonder - what happened to the class NautilusDesktopWindow? It was reserved for the desktop window - transparent invisible window with grid for icons (I think). The manual addition of this class to the theme css file does nothing. Maybe it's time to check the source code of the Nautilus? I hate that but it takes too long. Time to try.

**Comment by khurshid-alam** [comment]
With Adwaita, Nautilus takes both "**Adwaita.css**" and "**nautilus.css**" while giving the application higher level priority, and Gtk seems to give the `provider added last` a higher priority. It works fine as long as **nautilus,.css** is added **last** (which is what we are doing)...but breaks things while changing theme. Reloading every nautilus instances fixes the issue.

"**nautilus.css**" uses an element selector ("`nautilus-desktop-window"`) while "`Adwaita.css`" uses a class based selector ("`.nautilus-window`") to change the background. However class selectors always take priority over element selectors. The problem is `nautilus-desktop-window` also has the "`.nautilus-window`" class. So, the ideal option is to use `.nautilus-window` class and set background color transparent in [gtk-3.20/scss/apps/_nautilus.scss#L34](https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/apps/_nautilus.scss#L34)

If this isn't a bug in gtk, then its a bug in nautilus.

**Comment by ikuraj** [comment]
I am not sure whether a concensus was reached, but it seems the issue pertains to this particular theme. I could not solve the issue with some of the fixes proposed here, so I just changed my theme to get the background image back.

**Comment by megax** [comment]
Fixed bug, removed paned code. #482
Sample:
![image](https://cloud.githubusercontent.com/assets/461493/15991722/92a23e2c-30bb-11e6-8cfd-6eefa4f02d4b.png)

**Comment by megax** [comment]
@ItachiSan @khurshid-alam Tested? Fixed? :)

**Comment by geckolinux** [comment]
Hi, this still seems to be a problem with openSUSE Tumbleweed:

![alt](https://bugzilla.opensuse.org/attachment.cgi?id=690319)

Complete bug report: https://bugzilla.opensuse.org/show_bug.cgi?id=982134

**Comment by megax** [comment]
@geckolinux Please test the latest version Numix theme (git -> master).

**Comment by geckolinux** [comment]
@megax Thanks, I'll test that and get back with you. But is this a Nautilus bug or a Numix bug? Because in the Nautilus changelog (in my screenshot) I see fixes for this bug too.

**Comment by megax** [comment]
so - so :)

**Comment by ItachiSan** [comment]
@megax I am still waiting for the package update (from Antergos).
Will report as soon as I test.

**Comment by geckolinux** [comment]
OK, on openSUSE Tumbleweed with Gnome 3.22 this is _partially_ fixed. Now there is a new bug where Nautilus is showing a narrow vertical white fringe on the extreme right vertical side of the screen. Look closely at the attached screenshot. The fringe goes away when desktop icons are disabled.

![screenshot from 2016-09-24 14-30-58](https://cloud.githubusercontent.com/assets/2692138/18810770/f17ebbba-8263-11e6-9db5-da06440f0896.png)

**Comment by axfelix** [comment]
I think that may already be fixed in master, I noticed it prior to the last update on Arch but not in the most recent one.

**Comment by geckolinux** [comment]
@axfelix Ah, nice, I'll post back here if the fix appears in Tumbleweed.

**Comment by ItachiSan** [comment]
@megax fixed! Thanks a lot :smile:
