### ISSUE TITLE
Overlapping dark terminals have no visible border

### ISSUE THREAD

**Issue by fidian** [numixproject/numix-gtk-theme#287]
I have a hard time telling my terminals apart.  Is there a way I can edit `.config/gtk-3.0/gtk.css` or modify the Numix theme so that terminals can have a border of some sort?  I've tried many incantations but continually fail.  Perhaps it is because I use Ubuntu Gnome (not Unity) and half of the CSS suggestions are for Unity or modifying the Unity plugin with Compiz.

I feel that this is a bug in the theme itself, but I am uncertain if themes aim to support edge cases like this.  I would happily accept any solution at this point.

Attached is a screen shot illustrating the problem.

![screenshot from 2016-01-26 08-03-46](https://cloud.githubusercontent.com/assets/428348/12584184/e3f6729c-c40b-11e5-8805-e2fef5e06e30.png)

**Comment by khurshid-alam** [comment]
Which distro? Gnome-version? Because on 3.18, Numix from git master looks like this:

![image1](http://i.imgur.com/N7NmtsW.png)

And it is using 1px margin for csd windows

**Comment by fidian** [comment]
Ubuntu Gnome 14.10.  Unsure how to get the gnome version.

Try setting your terminal to have a black background instead of white.

**Comment by khurshid-alam** [comment]
Are you using Numix from the PPA?

14.10 has Gnome 3.12. The theme design (and code) has changed so much since then, its hard to pinpoint the issue. Any it looks like the issue with csd window margin. Try Numix from git master. Or upgrade your OS to 15.10

**Comment by fidian** [comment]
Sorry, I meant to say 15.10.  Typo.

I tried Numix from git master.  Whoa, that did not work at all.  Windows lost their backgrounds and title bars.

![screenshot from 2016-01-27 12-42-06](https://cloud.githubusercontent.com/assets/428348/12624240/99a20e7a-c4f3-11e5-872b-09f1fd89fdff.png)

**Comment by khurshid-alam** [comment]
Git master is using sass. You need to to run `scss --update` to make it work. Refer to the readme file.

**Comment by khurshid-alam** [comment]
Ok. On Ubuntu, installation is bit complected.
- **1**
  
  Install dependencies:
  `sudo apt-get install ruby-sass libgdk-pixbuf2.0-dev libxml2-utils libglib2.0-bin`
- **2**

`git clone git@github.com:shimmerproject/Numix.gitgit@github.com:shimmerproject/Numix.git Numix-Git`
- **3**

Go inside Numix-Git and open `index.theme`. Change `Name`, `GtkTheme` &
`MetacityTheme` fields to `Numix-Git`

Open Makefile. Change `INSTALL_DIR` feild to `$(DESTDIR)/usr/share/themes/Numix-Git`
- **4**

Now open terminal in the folder and run:

`make`

`sudo make install`
- **5**

Use tweak tool and change the theme to Numix-Git.

**DONE!**

**Comment by fidian** [comment]
Ok, so I have done this as well.

![screenshot from 2016-01-28 07-05-33](https://cloud.githubusercontent.com/assets/428348/12645146/a817ccb6-c58d-11e5-969c-71141a014388.png)

Could someone here take the time to change their terminal to use a "white on black" scheme as shown in this next screen shot.  You can see the git version of Numix styling the drop-down box.

![screenshot from 2016-01-28 07-07-44](https://cloud.githubusercontent.com/assets/428348/12645192/d86d543a-c58d-11e5-963c-69841c1c95f6.png)

Again, I realize that perhaps terminals colored this way are not supposed to be supported by Numix.  I'm just seeking that this is supported or that a workaround could be provided.  I'm not smart enough with GTK CSS to make that happen.

**Comment by khurshid-alam** [comment]
Yes, when using White on black scheme, the window border color becomes same as black...hence not properly visible. 

On Ubuntu-Gnome, gnome-terminal uses csd and this bug **doesn't** exits for GTK>=3.18

On Unity, it uses Unity decorator.  I changed the Unity window backdrop color and it looks like this:
![image1](http://i.imgur.com/24rL6Pc.png)

I will create a pull request after testing this a bit more.

**Comment by fidian** [comment]
I don't understand the acronym "csd".

Is there some workaround I can add to `.config/gtk-3.0/gtk.css` to make a border that's exactly like what you show appear for me?

**Comment by rafaelsms** [comment]
I installed numix from ppa and today after a reboot my terminal got from black background with green, gray and blue font to white l background and green black font
Is there a way to go back to the default ppa one (dark background)?

**Comment by fidian** [comment]
I believe the terminal colors and background are controlled by the terminal's profile properties.  Right click in the window, edit the profile preferences and pick another color scheme.

**Comment by khurshid-alam** [comment]
This has been fixed with new terminal design.

**Comment by fidian** [comment]
I've cloned the repository, rebuilt and installed the theme again.  This problem still exists.

![image](https://cloud.githubusercontent.com/assets/428348/14078231/a517be1c-f4b9-11e5-9fe7-f2ad3936bc7e.png)

**Comment by khurshid-alam** [comment]
@fidian You first need to remove the theme. Then you can install it from PPA. There is no need to compile it anymore.

Under Ubuntu-Gnome 16.04 it looks like this:

![pic](http://i.imgur.com/Xfb27Me.png)

**Comment by fidian** [comment]
You probably missed it, but I am using the "white on black" color scheme with my terminal.  You are not.  Would you post a picture of it working with the palette adjusted to match mine, as you've seen in all of my screen shots?

**Comment by khurshid-alam** [comment]
Supporting each and every color scheme is not possible. It is same for any other gtk theme including Adwaita (they use dark shadow). Beside AFAIK, custom color schemes will be removed from terminal in Gnome-3.22/Gtk-3.22

**Comment by fidian** [comment]
Is it not possible to make my screen look like your screen shot on Jan 28?  There you have the white on black color scheme and there is also a gray border around your windows.

I do understand that you can't support every color scheme and that terminals are different than every other thing out there.  My question is how come I can load up my browser and go to [http://blackle.com](http://blackle.com) and see a wonderful gray border, but I don't see one for my terminal?  Is there anything I can do to make the border appear for the terminal?

![screenshot from 2016-03-28 12-48-26](https://cloud.githubusercontent.com/assets/428348/14085096/8a602e18-f4e3-11e5-80cf-04ae9a420e55.png)

**Comment by khurshid-alam** [comment]
@fidian There are csd (client side) and ssd (like chrome browse) decoration. Window managers are responsible for providing composting. Ubuntu uses its own decorator but compiz does not support GTK_FRAME_EXTENT which is required to render everything perfectly. So there are some inconsistency between mutter(Gnome-Shell) and compiz.

The white window frame border produces these bugs under compiz: #281 #206

**Comment by fidian** [comment]
First off, I would like to say thanks for trying to tell me the details about why this problem exists.  I'll be honest and say it isn't quite sinking in, and I suspect that's due to a lack of knowledge.  I might need you to dumb down your answers to what a slightly techy "end user" might understand.

My problem is that my terminals blur together and I don't know if there is a workaround or a way for me to fix it.  What options do I have?  Switch from Ubuntu Gnome to Unity?  Patch compiz to support GTK_FRAME_EXTENT (probably beyond my skill level)?  Wait for GTK >= 3.18?  Use a terminal that uses ssd decoration (are there any)?  Would all of these work, or do you have other options that may work?

Is there a way I can buy you a beer or something for the extra work you've put in to help me out?

**Comment by khurshid-alam** [comment]
Gnome-Terminal 3.18 doesn't use csd. If it does, it can probably be decorated separately without affecting other things. Now, one option is to modify css under source; other is to use slightly lighter dark color as background and keep shadow color darker (i.e #2D2D2D).

Under Unity your problem is solved as you decorate window frame border (as shown in the above image). 

I think situation will improve in 3.20.

**Comment by fidian** [comment]
Could you explain the "modify css under source" bit?  I've spent about three hours trying to figure out the CSS selectors to add a border to terminal windows to no avail.  This was back in January before I opened the ticket and another couple hours in February.  Are you talking about modifying the Numix theme's CSS or something in Gnome-Terminal?

**Comment by aantos** [comment]
I have the same problem (hardly separable overlapping terminals with White-on-black or Green-on-black scheme due to lack of visible border) with recent Debian Stretch (testing, Gnome 3.20, Gtk+3 3.20, and Gtk+2 2.24).  So it does not seem to be specific/related to either Ubuntu, Compiz, old Gnome versions, or Numix. I use the default gnome-shell and default gtk theme Adwaita (as can be seen on my screenshot). I only switch the Built in scheme on the Color tab of Profile preferences to Green-on-black, that is available in the default install.
In some earlier versions, this worked fine, but some of the upgrade caused this regression without changing user setup. So I definitely consider this a bug that ought to be fixed somewhere (in gnome, gtk?).
 I think the default theme should support at least the seven pre-installed default color schemes as a minimum. Note that green/white-on-black are not custom color schemes. Also that, Unity is not an option in Debian and several other distros.
Is it correct that the issue is not that we do not have window border at all, but that the border has the very same black color as the background?

![screenshot20160905gnome-terminal](https://cloud.githubusercontent.com/assets/3883089/18252159/8c3a163a-738d-11e6-942d-e3ae6728bd4a.png)

**Comment by Light--** [comment]
same problem here, may i ask how to fix it to look like yours? 
@khurshid-alam

**Comment by dbooth-boston** [comment]
same problem

**Comment by makermarc** [comment]
I found the solution here...
https://askubuntu.com/questions/976030/how-to-enable-add-window-borders-in-17-10-18-04

These are the steps that worked for me: 
```
# Create gtk.css file
nano ~/.config/gtk-3.0/gtk.css

# Add the lines:
decoration {
  border: 1px solid gray;
  background: gray;
}
```

Save the file and then use: 

Use [ALT]+F2, enter 'r' to restart the shell.

---------------------------------------------

OS: Ubuntu 21.10
GNome Version 40.4.0
