### ISSUE TITLE
Bad location bar in Nautilus with GNOME 3.30

### ISSUE THREAD

**Issue by ogarcia** [numixproject/numix-gtk-theme#721]
The location bar in nautilus have bad colors in GNOME3.30 when is maximized.
![location_bar](https://user-images.githubusercontent.com/572924/46596511-27da4800-cadd-11e8-9f49-390f0f7d130f.png)
I'm using trunk.

**Comment by khurshid-alam** [comment]
Gnome 3.30 broke the breadcrumbs.I don't think it can selectively fixed for two different nautilus version.

For now append this to ~/.config/gtk-3.0/gtk.css

.```
nautilus-window .path-bar-box {
  border-radius: 2px;
}

.nautilus-window .path-bar > box > button {
  background-color: transparent;
  border-color: transparent;
  border-radius: 0;
  margin: 0 2px;
  padding: 1px;
}

.nautilus-window .path-bar > box > button:hover {
  box-shadow: 0 -3px rgb(99, 99, 200) inset;
}
```

**Comment by fossfreedom** [comment]
3.30.2 version of nautilus should have reverted the changes that broke 3rd party themes.

If someone can confirm then this bug could be closed.

**Comment by ogarcia** [comment]
I have 3.30.1 and seems fixed. But if you want I can wait to 3.30.2 to make definitive check.

UPDATE:
No, sorry. I have 3.30.1 in about but nautilus is 3.30.2. And yes, is fixed.
![location_bar](https://user-images.githubusercontent.com/572924/47501351-9ea96c00-d865-11e8-93c5-bcf84b189b7e.png)

**Comment by patriziobruno** [comment]
As far as I can tell there's still a problem there. The location bar should have a different background than the rest of the headerbar, to avoid funny alignments of both the location bar and the search button.
